name: Publishing

on:
  push:
    tags:
      # Publish on any tag starting with a `v`, e.g. v1.2.3
      - v*

jobs:
  # checks:
  #   uses: ./.github/workflows/shared.yml

  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    # needs:
    #   - checks
    environment:
      # Create this environment in the GitHub repository under Settings -> Environments
      name: release
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv build
      - run: uv publish --trusted-publishing always
